# Generated by Django 4.1 on 2022-09-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviar_email', '0002_alter_noticia_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='filter',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='lingua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
