# Generated by Django 4.1.1 on 2022-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuario_filtro_alter_usuario_lingua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='lingua',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='filtro',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.TextField(blank=True, default="['pt BR']", max_length=300, null=True),
        ),
    ]
